# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425fbe4a48f35b2315547ff320ca33aa069e9dee355bf1e9807fb4d7ee604e55ec1dedc088996885f933dc45985f604a86a61a3b91a75cfe056380cfefd90842

test:
  secret_key_base: 9710514c30742e4c594cf0577b2cbce25ac4d4389d221bed44a0c6021ee0abceeb240e406819ae7dda82bb7d977dd54319c1e369bc4f11875b93b5e6b807abd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
